//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExMachinaLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExMachinaLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить профиль игры.
        /// </summary>
        public static string BackUpMainProfileBtn {
            get {
                return ResourceManager.GetString("BackUpMainProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение работает ТОЛЬКО для профиля в игре без модификаций.
        ///Что бы сохранить профиль модификации воспользуйтесь кнопкой &quot;Выгрузить модификацию&quot;.
        ///
        ///Продолжить?.
        /// </summary>
        public static string BackUpProfile {
            get {
                return ResourceManager.GetString("BackUpProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из папки с игрой будут удалены все установленные модификации. 
        ///Профиль игрока так же будет удалён.
        ///Будут восстановлены родные файлы игры.
        ///
        ///Продолжить?.
        /// </summary>
        public static string ClearDataWarning {
            get {
                return ResourceManager.GetString("ClearDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить игру.
        /// </summary>
        public static string CleareDataBtn {
            get {
                return ResourceManager.GetString("CleareDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете этого сделать.
        ///Обнаружена установленная модификация. 
        ///Воспользуйтесь кнопкой &quot;Выгрузить модификацию&quot;, а затем повторите попытку..
        /// </summary>
        public static string errorLoadBackUpProfile {
            get {
                return ResourceManager.GetString("errorLoadBackUpProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string ExitBtn {
            get {
                return ResourceManager.GetString("ExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль игрока успешно сохранён..
        /// </summary>
        public static string infoBackUpProfile {
            get {
                return ResourceManager.GetString("infoBackUpProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра успешно очищена.
        ///Вы можете начать новую игру или загрузить сохранённый профиль..
        /// </summary>
        public static string infoClean {
            get {
                return ResourceManager.GetString("infoClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль игрока успешно загружен..
        /// </summary>
        public static string infoLoadProfile {
            get {
                return ResourceManager.GetString("infoLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  загружен успешно!.
        /// </summary>
        public static string infoLoadWindow {
            get {
                return ResourceManager.GetString("infoLoadWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация:.
        /// </summary>
        public static string InfoTb {
            get {
                return ResourceManager.GetString("InfoTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  модификация успешно выгружена. 
        ///Профиль игрока сохранён в папке с модификацией..
        /// </summary>
        public static string infoUnload {
            get {
                return ResourceManager.GetString("infoUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выгрузить модификацию, у вас чистая игра.
        ///Можете загрузить модификацию или играть в чистую игру..
        /// </summary>
        public static string infoUnloadModExeption {
            get {
                return ResourceManager.GetString("infoUnloadModExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список модификаций:.
        /// </summary>
        public static string ListModTA {
            get {
                return ResourceManager.GetString("ListModTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загруженная модификация:.
        /// </summary>
        public static string LoadedModTB {
            get {
                return ResourceManager.GetString("LoadedModTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить профиль игры.
        /// </summary>
        public static string LoadMainProfileBtn {
            get {
                return ResourceManager.GetString("LoadMainProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пытаетесь установить модификацию поверх ранее установленной.
        ///Не делайте этого, если модификации не являются совместимыми.
        ///Если вы не уверены в совместимости модификаций - нажмите кнопку &quot;Отмена&quot;.
        ///
        ///
        ///Продолжить?.
        /// </summary>
        public static string loadManyModWarning {
            get {
                return ResourceManager.GetString("loadManyModWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить модификацию.
        /// </summary>
        public static string LoadModBtn {
            get {
                return ResourceManager.GetString("LoadModBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед установкой модификации рекомендовано выполнить очистку игры при помощи кнопки &quot;Очистить игру&quot;.
        ///Все сохранения при этом будут утеряны. 
        ///Что бы сохранить профиль игрока воспользуйтесь кнопкой &quot;Сохранить профиль&quot;..
        /// </summary>
        public static string loadModWarning {
            get {
                return ResourceManager.GetString("loadModWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка профиля работает ТОЛЬКО для в игре без модификаций.
        ///Профиль предварительно должен быть сохранён.
        ///
        ///Что бы загрузить ранее сохранённый профиль модификации воспользуйтесь кнопкой &quot;Загрузить модификацию&quot;.
        ///
        ///Продолжить?.
        /// </summary>
        public static string LoadProfile {
            get {
                return ResourceManager.GetString("LoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лаунчер установлен не полностью.
        ///Пожалуйста, переустановите лаунчер.
        ///Лаунчер должен находиться в корневой папке игры на одном уровне с файлами ExMachina.exe или HTA.exe..
        /// </summary>
        public static string noExe {
            get {
                return ResourceManager.GetString("noExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет загруженных модификаций.
        /// </summary>
        public static string NoLoadedMods {
            get {
                return ResourceManager.GetString("NoLoadedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обнаружено установленных модификаций.
        ///Некоторые функции программы могут быть недоступны..
        /// </summary>
        public static string NoMods {
            get {
                return ResourceManager.GetString("NoMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет модификаций.
        /// </summary>
        public static string NoModsName {
            get {
                return ResourceManager.GetString("NoModsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeusExMachina.
        /// </summary>
        public static string SiteBtn {
            get {
                return ResourceManager.GetString("SiteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить игру.
        /// </summary>
        public static string StartGameBtn {
            get {
                return ResourceManager.GetString("StartGameBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить игру с консолью.
        /// </summary>
        public static string StartGameConsoleBtn {
            get {
                return ResourceManager.GetString("StartGameConsoleBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгружая модификации вы сохраняете игровой профиль модификаций в папке с ПОСЛЕДНЕЙ загруженной модификацией.
        ///При повторной установке модификаций в том же порядке, в котором они были установлены до выгрузки модификаций, у вас будут сохранены все ваши предыдущие достижения.
        ///
        ///Продолжить?.
        /// </summary>
        public static string UnloadManyModExeption {
            get {
                return ResourceManager.GetString("UnloadManyModExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузить модификацию.
        /// </summary>
        public static string UnloadModBtn {
            get {
                return ResourceManager.GetString("UnloadModBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгружая модификацию вы сохраняете игровой профиль модификации в папке с модификацией.
        ///При повторной установке модификации у вас будут сохранены все ваши предыдущие достижения.
        ///
        ///Продолжить?.
        /// </summary>
        public static string UnloadSingleModExeption {
            get {
                return ResourceManager.GetString("UnloadSingleModExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание:.
        /// </summary>
        public static string WarningTb {
            get {
                return ResourceManager.GetString("WarningTb", resourceCulture);
            }
        }
    }
}
